apiVersion: v1
kind: Namespace
metadata:
  name: rook
---
apiVersion: rook.io/v1alpha1
kind: Cluster
metadata:
  name: rook
  namespace: rook
spec:
  dataDirHostPath: /mnt/ssddata/rook
  storage:
    useAllNodes: false
    useAllDevices: false
    deviceFilter:
    metadataDevice:
    location:
    storeConfig:
      storeType: filestore
      databaseSizeMB: 1024 # this value can be removed for environments with normal sized disks (100 GB or larger)
      journalSizeMB: 1024  # this value can be removed for environments with normal sized disks (20 GB or larger)
    nodes:
    - name: "mothership"
      directories:         # specific directores to use for storage can be specified for each node
      - path: "/mnt/ssddata/rook"
    #- name: "172.17.4.201"
    #  devices:             # specific devices to use for storage can be specified for each node
    #  - name: "sdb"
    #  - name: "sdc"
    #  storeConfig:         # configuration can be specified at the node level which overrides the cluster level config
    #    storeType: bluestore
    #- name: "172.17.4.301"
    #  deviceFilter: "^sd."