apiVersion: v1
kind: Secret
metadata:
  name: wio1-secret
type: Opaque
data:
  token: {{ .Values.wio1.token }}
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: soil1
spec:
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  schedule: "*/20 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: soil1
            image: sequenceiq/busybox
            env:
            - name: API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: wio1-secret
                  key: token
            args:
            - /bin/sh
            - -c
            - curl -i -XPOST 'http://influxdb-influxdb:8086/write?db=leetbase' --data-binary "soil1,wionode=test1 value=$(curl -k "https://us.wio.seeed.io/v1/node/GenericAInA0/analog?access_token=${API_TOKEN}" | jq .analog)"
          restartPolicy: OnFailure