apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: grafana-ingress
  namespace: default
spec:
  rules:
    - host: idealeet
      http:
        paths:
          - backend:
              serviceName: grafana
              servicePort: 80
            path: /
