apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: soil1
spec:
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  schedule: "*/20 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: soil1
            image: sequenceiq/busybox
            args:
            - /bin/sh
            - -c
            - curl -i -XPOST 'http://192.168.1.200:31316/write?db=leetbase' --data-binary "soil1,wionode=test1 value=$(curl -s "https://us.wio.seeed.io/v1/node/GenericAInA0/analog?access_token=6bb3a73ba99502614dc1abed69d8da01" | jq .analog)"
          restartPolicy: OnFailure