kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: influxdb-pvc
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: local-pv-2
  storageClassName: local-storage